import type { Bilingual } from '../types'

/**
 * Editorial "Key takeaway" for each chart, keyed by ChartData.id.
 *
 * These are interpretive insights — distinct from the factual data that the
 * Google-Sheets sync owns. They deliberately live HERE, not in the per-chart
 * JSON under web/src/data/*.json, because those JSON files are regenerated by
 * scripts/sync_from_sheets.py on every sync; any field the parser does not
 * emit (and it only emits title/subtitle/methodology/source) would be wiped.
 * Keeping takeaways in this standalone module decouples them from that pipeline.
 *
 * To edit a takeaway, change the text below — it will not be overwritten by a
 * Sheets sync. To add one for a new chart, add an entry keyed by the chart id.
 */
export const TAKEAWAYS: Record<string, Bilingual> = {
  'students-new': {
    th: 'การรับนักศึกษาใหม่ขยายตัวกว่า 5 เท่าจากต้นทศวรรษ 2530 สู่จุดสูงสุดราว 5,700 คนในปี 2549 จากนั้นลดลงมาทรงตัวที่ ~4,000–4,500 คน โดยการลดลงมาจากระดับบัณฑิตศึกษาเป็นหลัก ขณะที่ระดับปริญญาตรีค่อนข้างคงที่',
    en: "New enrolment expanded more than 5× from the early 1990s to a peak of ~5,700 in 2006, then settled at ~4,000–4,500. The decline is driven mainly by graduate intake, while bachelor's intake holds steady.",
  },
  'students-all': {
    th: 'จำนวนนักศึกษาทั้งหมดเพิ่มขึ้นราว 3 เท่าสู่จุดสูงสุด ~17,900 คนในปี 2556 ก่อนลดลงมาที่ ~14,700 คน ระดับปริญญาตรีทรงตัวราว 12,000 คน ขณะที่บัณฑิตศึกษาลดลงกว่าครึ่งจากจุดสูงสุด ทำให้สัดส่วนนักศึกษาเอนไปทางปริญญาตรีมากขึ้น',
    en: "Total enrolment roughly tripled to a peak of ~17,900 in 2013 before easing to ~14,700. Bachelor's has plateaued near 12,000 while graduate enrolment more than halved from its peak, shifting the student mix back toward undergraduates.",
  },
  'programs': {
    th: 'จำนวนสาขาวิชารวมค่อนข้างคงที่ (~150 สาขา) แต่โครงสร้างกำลังเป็นสากลมากขึ้น หลักสูตรนานาชาติเพิ่มจาก 34 เป็น 45 สาขา (+32%) ขณะที่หลักสูตรภาษาไทยลดลงเล็กน้อย',
    en: 'The total program count is stable (~150), but the mix is internationalising — international programs grew from 34 to 45 (+32%) while Thai programs edged down.',
  },
  'graduates': {
    th: 'จำนวนผู้สำเร็จการศึกษาต่อปีเพิ่มขึ้นราว 6 เท่าสู่จุดสูงสุด ~4,300 คนในปี 2556 ตามการขยายตัวของการรับเข้าโดยมีช่วงเวลาเหลื่อม จากนั้นทรงตัวที่ ~3,300–3,600 คน โดยระดับบัณฑิตศึกษาลดลงมากที่สุด',
    en: 'Annual graduates grew ~6× to a peak of ~4,300 in 2013, tracking the enrolment boom with a lag, then settled near 3,300–3,600 — with graduate-level completions falling the most.',
  },
  'employment-bachelor': {
    th: 'การมีงานทำภายใน 1 ปีของบัณฑิตปริญญาตรีปกติอยู่ที่ ~60–80% และผันผวนตามภาวะเศรษฐกิจ ตัวเลขที่ดูต่ำในปี 2567 (49%) เกิดจากช่วงเก็บข้อมูลที่ยังไม่ครบ 1 ปี ไม่ใช่การจ้างงานที่ลดลงจริง',
    en: "Bachelor's employment within a year typically runs 60–80% and swings with the economy. The low 2024 figure (49%) reflects an incomplete <1-year survey window, not a real drop in hiring.",
  },
  'employment-graduate': {
    th: 'การมีงานทำของบัณฑิตระดับบัณฑิตศึกษาแข็งแกร่งและสม่ำเสมอ อยู่ที่ ~82–93% ภายใน 1 ปีตลอดสามทศวรรษ และผันผวนน้อยกว่าระดับปริญญาตรีมาก',
    en: "Graduate-level employment is consistently strong — 82–93% employed within a year across three decades, and far more stable than bachelor's outcomes.",
  },
  'staff-total': {
    th: 'บุคลากรรวมเพิ่มขึ้นราว 3.4 เท่าเป็น ~2,650 คน แต่โครงสร้างพลิกหลังเป็นมหาวิทยาลัยในกำกับของรัฐในปี 2541 ตำแหน่งข้าราชการลดจาก ~900 เหลือ 61 คน ขณะที่ตำแหน่งพนักงานมหาวิทยาลัยเพิ่มจากศูนย์เป็น ~1,800 คน',
    en: 'Total staff grew ~3.4× to ~2,650, but the composition flipped after KMUTT became autonomous in 1998: civil-servant posts shrank from ~900 to 61, while university-employee positions grew from zero to ~1,800.',
  },
  'faculty-degree': {
    th: 'จำนวนบุคลากรสายวิชาการทรงตัว (~890 คนตั้งแต่กลางทศวรรษ 2550) แต่คุณวุฒิสูงขึ้นชัดเจน ผู้จบปริญญาเอกเพิ่มจาก 54 เป็น 696 คน (ราว 78% ของอาจารย์) ขณะที่อาจารย์วุฒิปริญญาตรีแทบหมดไป',
    en: "Academic staff size has plateaued (~890 since the mid-2010s), but qualifications have risen sharply — doctorate-holders grew from 54 to 696 (now ~78% of faculty), while bachelor's-only faculty nearly vanished.",
  },
  'staff-academic-support': {
    th: 'สัดส่วนบุคลากรสายวิชาการลดลงจาก ~39% (2551) เหลือ ~34% (2568) โดยสายสนับสนุนเพิ่มเป็นสองในสามของกำลังคน เป็นประเด็นที่ควรติดตามเทียบกับพันธกิจด้านการสอนและวิจัย',
    en: 'The academic-staff share has slipped from ~39% (2008) to ~34% (2025), with support staff now two-thirds of the workforce — worth watching against the teaching and research mission.',
  },
  'research-funding': {
    th: 'งบประมาณวิจัยเติบโตราว 14 เท่าในสามทศวรรษสู่ระดับ ~500 ล้านบาท ขับเคลื่อนหลักด้วยทุนแข่งขันจากแหล่งภายนอก โดยตั้งแต่ปี 2563 งบประมาณแผ่นดินถูกรวมเข้ากับแหล่งทุนภายนอก',
    en: 'Research funding grew ~14× over three decades to ~500M฿, driven overwhelmingly by external competitive grants. From 2020, national-budget allocations were folded into external funding.',
  },
  'research-funding-3yr': {
    th: 'เมื่อดูค่าเฉลี่ย 3 ปี งบประมาณวิจัยเพิ่มขึ้นต่อเนื่องจาก ~35 เป็น ~486 ล้านบาท ยืนยันการเติบโตระยะยาวที่มั่นคงแม้มีความผันผวนรายปีจากโครงการก้อนใหญ่',
    en: 'On a 3-year smoothed basis, research funding rose steadily from ~35M฿ to ~486M฿, confirming sustained long-term growth despite year-to-year volatility from large one-off grants.',
  },
  'research-per-staff': {
    th: 'ความเข้มข้นของทุนวิจัยต่อบุคลากรที่ทำงานวิจัยจริงเพิ่มขึ้นราว 4 เท่าเป็น ~1.3 ล้านบาท/คน สะท้อนว่าทุนวิจัยเติบโตเร็วกว่ากำลังคนวิจัย',
    en: 'Funding intensity per active researcher roughly quadrupled to ~1.3M฿, signalling that grants have grown faster than the research workforce.',
  },
  'research-per-staff-3yr': {
    th: 'เมื่อเฉลี่ย 3 ปี ทุนวิจัยต่อบุคลากรที่ทำงานวิจัยเพิ่มจาก ~0.36 เป็น ~1.21 ล้านบาท/คน เป็นแนวโน้มขาขึ้นชัดเจนของความเข้มข้นด้านการวิจัย',
    en: 'Smoothed over three years, funding per active researcher climbed from ~0.36 to ~1.21M฿ — a clear long-run rise in research intensity.',
  },
  'research-per-academic-3yr': {
    th: 'ทุนวิจัยต่อบุคลากรสายวิชาการเพิ่มขึ้นราว 6 เท่า (0.10 → 0.61 ล้านบาท/คน จากค่าเฉลี่ย 3 ปี) สะท้อนทั้งทุนที่เพิ่มขึ้นและจำนวนอาจารย์ที่ค่อนข้างคงที่',
    en: 'Research funding per academic staff member grew ~6× (0.10 → 0.61M฿ on a 3-year average), reflecting both rising grants and a stable faculty headcount.',
  },
  'publications': {
    th: 'ผลงานตีพิมพ์เพิ่มขึ้นราว 7 เท่าเป็นกว่า 1,400 ชิ้น/ปี และโครงสร้างขยับสู่แหล่งคุณภาพสูงขึ้น บทความวารสารนานาชาติเพิ่มเป็น ~830 ชิ้น/ปี ขณะที่รายงานการประชุมลดลงมากตั้งแต่กลางทศวรรษ 2550',
    en: 'Output grew ~7× to over 1,400/year, and the mix shifted toward higher-impact venues — international-journal articles climbed to ~830/year while conference proceedings fell sharply since the mid-2010s.',
  },
  'publications-3yr': {
    th: 'ภาพค่าเฉลี่ย 3 ปีทำให้การขยับด้านคุณภาพชัดเจน บทความวารสารนานาชาติเพิ่มราว 14 เท่า ขณะที่รายงานการประชุมขึ้นสูงสุดช่วงปี 2551–2557 แล้วลดลง',
    en: 'The 3-year view makes the quality shift clear — international-journal output rose ~14×, while conference proceedings peaked around 2008–2014 and then declined.',
  },
  'publications-per-academic': {
    th: 'ผลิตภาพต่ออาจารย์ขึ้นสูงสุดราว 1.9 บทความ/คนช่วงปี 2550–2551 จากนั้นทรงตัวที่ ~1.2–1.6 แม้ผลงานรวมยังสูง สะท้อนฐานอาจารย์ที่ใหญ่ขึ้นและการขยับไปตีพิมพ์ในวารสาร',
    en: 'Per-faculty productivity peaked near 1.9 papers/person around 2007–2008 and has since settled at ~1.2–1.6, even as total output stayed high — reflecting a larger faculty base and a shift toward journals.',
  },
  'patents': {
    th: 'การยื่นขอสิทธิบัตร/อนุสิทธิบัตรสะสมแตะ 736 คำขอ (ได้รับแล้ว 323) การยื่นรายปียังไม่มาก (~15–30) แต่อัตราการได้รับเพิ่มขึ้นชัดเจนตั้งแต่ราวปี 2559',
    en: 'Cumulative patent and petty-patent filings reached 736 (323 granted). Annual filings remain modest (~15–30), but the grant rate has improved markedly since ~2016.',
  },
  'income-expense': {
    th: 'รายรับเติบโตราว 10 เท่านับตั้งแต่เป็นมหาวิทยาลัยในกำกับฯ (2541) แต่ระยะหลังรายจ่ายโตเร็วกว่า ปีงบประมาณ 2566–2568 ขาดดุลเป็นครั้งแรกในประวัติศาสตร์ เป็นการเปลี่ยนเชิงโครงสร้างที่ควรติดตามใกล้ชิด',
    en: 'Revenue grew ~10× since autonomy (1998), but expenditure has recently grown faster — FY2023–2025 posted the first operating deficits on record, a structural shift worth close monitoring.',
  },
  'income-expense-3yr': {
    th: 'เมื่อเฉลี่ย 3 ปี รอบ 2566–2568 เป็นรอบแรกที่ดุลสุทธิติดลบ ยืนยันว่าการขาดดุลล่าสุดเป็นแนวโน้ม ไม่ใช่เหตุการณ์ชั่วคราว',
    en: 'On a 3-year average, the 2023–2025 window is the first with a negative net balance, confirming the recent deficits are a trend rather than a one-off.',
  },
}
